version: 0.2

phases:
  build:
    commands:
      - git clone https://github.com/Hussain-L/webhook.git
      - sudo apt install zip
      - zip -r webhook.zip webhook
      - echo hey this works
      - aws s3 mv webhook.zip s3://webhook-hussain
